site_name: Aegir Hosting System
repo_url: https://github.com/aegir-project/documentation
theme: readthedocs
site_favicon: '_images/favicon.ico'
docs_dir: .
site_dir: '_site'
extra_css:
  - '_css/toc.css'
  - '_css/menu.css'
  - '_css/images.css'
pages:
- 'Home': 'index.md'
- 'Community': 'community.md'
- 'Community':
  - 'Code of Conduct': 'community/code-of-conduct.md'
  - 'Documentation': 'community/documentation.md'
