site_name: Aegir Hosting System
repo_url: https://github.com/aegir-project/documentation
theme: readthedocs
site_favicon: '_images/favicon.ico'
extra_css:
  - '_css/toc.css'
  - '_css/menu.css'
  - '_css/images.css'
pages:
- 'Home': 'index.md'
- 'Quick start': 'quick-start.md'
- 'Install': 'install.md'
- 'Using Aegir': 'usage.md'
- 'Using Aegir':
  - 'Sites': 'usage/sites.md'
  - 'Sites':
    - 'Site tasks': 'usage/sites/tasks.md'
    - 'Site aliases': 'usage/sites/aliases.md'
    - 'Importing sites': 'usage/sites/importing.md'
#  - 'Platforms': 'usage/platforms.md'
#  - 'Platforms':
#    - 'Platform tasks': 'usage/platforms/tasks.md'
#  - 'Servers': 'usage/servers.md'
#  - 'Servers':
#    - 'Server tasks': 'usage/servers/tasks.md'
  - 'Advanced features': 'usage/advanced.md'
  - 'Advanced features':
    - 'SSL': 'usage/advanced/ssl.md'
    - 'Multiple servers': 'usage/advanced/remote-servers.md'
    - 'Altering behaviours': 'usage/advanced/altering-behaviours.md'
    - 'Extending Aegir': 'usage/advanced/contrib-modules.md'
- 'Community': 'community.md'
- 'Community':
#  - 'Contacting the community': 'community/contact.md'
  - 'Contacting the community': 'help/contact.md'
  - 'Code of Conduct': 'community/code-of-conduct.md'
  - 'Release process': 'community/release-process.md'
- 'Release notes': 'release-notes.md'
- 'Release notes':
  - '3.0': 'release-notes/3.0.md'
  - '3.1': 'release-notes/3.1.md'
  - '3.2': 'release-notes/3.2.md'
