site_name: Aegir Hosting System
repo_url: https://github.com/aegir-project/documentation
theme: readthedocs
pages:
- ['index.md', 'Home']
- ['quick-start.md', 'Quick Start']
- ['install/install.md', 'Install']
- ['install/system-requirements.md', 'Install', 'System Requirements']
- ['install/debian.md', 'Install', 'Debian/Ubuntu']
- ['install/manual.md', 'Install', 'Manual']
- ['install/common-problems.md', 'Install', 'Common Problems']
- ['import/importing-sites.md', 'Importing Sites']
- ['import/aegir-backups.md', 'Importing Sites', 'From Aegir Backups']
- ['import/single-site.md', 'Importing Sites', 'Single Site Import']
- ['import/complete-drupal-install.md', 'Importing Sites', 'Complete Drupal Install']
