site_name: Aegir Hosting System
repo_url: https://github.com/aegir-project/documentation
theme: readthedocs
pages:
- ['index.md', 'Home']
- ['help/contact.md', 'Contacting the community']
- ['quick-start.md', 'Quick Start']
- ['install/install.md', 'Install']
- ['install/system-requirements.md', 'Install', 'System Requirements']
- ['install/debian.md', 'Install', 'Debian/Ubuntu']
- ['install/manual.md', 'Install', 'Manual']
- ['install/trouble-shooting.md', 'Install', 'Trouble-shooting']
- ['import/importing-sites.md', 'Importing Sites']
- ['import/remote-import.md', 'Importing Sites', 'Remote Import']
- ['import/single-site.md', 'Importing Sites', 'Single Site Import']
- ['import/complete-drupal-install.md', 'Importing Sites', 'Complete Drupal Install']
- ['hooking-into-aegir/hooking-into-aegir.md', 'Hooking into Aegir (site overrides)', 'Introduction']
- ['hooking-into-aegir/override-site-specifics.md', 'Hooking into Aegir (site overrides)', 'Overriding site specific PHP values']
- ['hooking-into-aegir/injecting-server-vhosts.md', 'Hooking into Aegir (site overrides)', 'Injecting into server-wide vhosts']
- ['hooking-into-aegir/injecting-into-htaccess.md', 'Hooking into Aegir (site overrides)', 'Injecting into platform-wide vhosts (.htaccess)']
- ['hooking-into-aegir/injecting-into-site-vhosts.md', 'Hooking into Aegir (site overrides)', 'Injecting into site vhosts']
- ['hooking-into-aegir/injecting-into-settings.md', 'Hooking into Aegir (site overrides)', 'Injecting into settings.php']
- ['hooking-into-aegir/injecting-into-drushrc.md', 'Hooking into Aegir (site overrides)', 'Injecting into drushrc.php']
- ['remote-servers/remote-servers.md', 'Remote Serves (Multiserver)', 'Remote Servers (Multiserver)']
- ['remote-servers/web-packs.md', 'Multiple Web Heads using the Pack module', 'Multiple Web Heads using the Pack module']
- ['remote-servers/web-clusters.md', 'Multiple Web Heads using the Cluster module', 'Multiple Web Heads using the Cluster module']
- ['remote-servers/remote-platforms.md', 'Adding a platform', 'Adding a platform']
- ['community/code-of-conduct.md', 'Community', 'Code of Conduct']
- ['community/release-process.md', 'Community', 'Release Process']
- ['community/contrib-modules.md', 'Community', 'Contributed-modules']
- ['release-notes/3.0-release-notes.md', 'Release Notes', 'Release 3.0 Notes']
- ['release-notes/3.1-release-notes.md', 'Release Notes', 'Release 3.1 Notes']
- ['release-notes/3.2-release-notes.md', 'Release Notes', 'Release 3.2 Notes']
- ['uninstall/uninstall.md', 'Uninstalling Aegir', 'Uninstalling Aegir']
