site_name: Aegir Hosting System
repo_url: https://github.com/aegir-project/documentation
theme: readthedocs
pages:
- 'Home': 'index.md'
- 'Quick Start': 'quick-start.md'
- 'Install':
  - 'Install': 'install/install.md'
  - 'System Requirements': 'install/system-requirements.md'
  - 'Debian/Ubuntu': 'install/debian.md'
  - 'Manual': 'install/manual.md'
  - 'Common Problems': 'install/common-problems.md'
  - 'Uninstalling Aegir': 'install/uninstall.md'
- 'Usage':
  - 'Importing Sites':
    - 'Importing Sites': 'import/importing-sites.md'
    - 'Remote Import':  'import/remote-import.md'
    - 'Single Site Import': 'import/single-site.md'
    - 'Complete Drupal Install': 'import/complete-drupal-install.md'
  - 'Hooking into Aegir (site overrides)': 'hooking-into-aegir.md'
  - 'Remote Serves (Multiserver)':
    - 'Remote Servers (Multiserver)': 'remote-servers/remote-servers.md'
    - 'Multiple Web Heads using the Pack module': 'remote-servers/web-packs.md'
    - 'Adding a platform': 'remote-servers/remote-platforms.md'
- 'Release Process': 'community/release-process.md'
